src/view/prediction/urls.py
from django.urls import path

from . import views

app_name = 'prediction'

urlpatterns = [
    path('', views.index, name='index'),
    path('download/', views.download_result_file, name='download_result_file'),
]

src/view/view/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('prediction.urls')),
]

urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

urlpatterns += static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)

src/view/prediction/forms.py
from django import forms


class UploadFileForm(forms.Form):
    csv_file = forms.FileField(
        label='Загрузите train.csv',
        widget=forms.FileInput(attrs={'class': 'form-control-file'})
    )

    def clean_csv_file(self):
        csv_file = self.cleaned_data['csv_file']
        if not csv_file.name.endswith('.csv'):
            raise forms.ValidationError('Only CSV files are allowed.')

src/view/prediction/views.py
import os

from django.http import HttpResponse
from django.core.paginator import Paginator
from django.conf import settings
from django.shortcuts import render, redirect
import logging

from .dataclass import Prediction
from .exceptions import PredictionsParseError
from .forms import UploadFileForm
from .services import get_prediction_data

logger = logging.getLogger(__name__)


def index(request):

    if request.method == 'POST':
        # Parse data
        form = UploadFileForm(
            request.POST,
            request.FILES or None
        )

        if form.is_valid():
            context = {
                'form': form
            }

            # Save csv to mediafiles dir
            try:
                csv_file = request.FILES['csv_file']
                with open('mediafiles/train.csv', 'wb') as destination:
                    for chunk in csv_file.chunks():
                        destination.write(chunk)
            except Exception:
                logger.critical('Error saving training data')

            # Get predictions
            data = None
            try:
                data = get_prediction_data()

                request.session['result_data'] = [obj.as_dict() for obj in data]
            except PredictionsParseError as e:
                logger.critical('Error parsing predictions training data %s', e)
            except Exception as e:
                logger.critical('Unexpected error whith parsing predictions training data %s', e)

            if data:
                paginator = Paginator(data, 50)
                page_number = request.GET.get('page')
                page_obj = paginator.get_page(page_number)
                context['page_obj'] = page_obj
            else:
                context['error_message'] = "Ошибка получения результата"

            return render(request, 'index.html', context)

    data = request.session.get('result_data', [])
    data = [Prediction(**obj) for obj in data]

    # Sort and find by id
    sort_param = request.GET.get('sort')
    if sort_param:
        if sort_param == 'asc':
            data = sorted(data, key=lambda x: x.percentage if x.percentage else 1)
        elif sort_param == 'desc':
            data = sorted(data, key=lambda x: x.percentage if x.percentage else 1, reverse=True)

    find_id_param = request.GET.get('find_id')
    if find_id_param:
        data = [obj for obj in data if obj.customer_id == find_id_param]

    # Pagination
    paginator = Paginator(data, 50)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    form = UploadFileForm()
    context = {
        'page_obj': page_obj,
        'form': form
    }
    return render(request, 'index.html', context)


def download_result_file(request):
    file_path = os.path.join(settings.MEDIA_ROOT, 'result.csv')

    not_docker_file_path = os.path.join(settings.BASE_DIR, '../ai/mediafiles/result.csv')

    if not os.path.exists(file_path) and not os.path.exists(not_docker_file_path):
        return redirect('prediction:index')

    if os.path.exists(not_docker_file_path):
        file_path = not_docker_file_path

    with open(file_path, 'rb') as file:
        response = HttpResponse(file.read(), content_type='application/force-download')
        response['Content-Disposition'] = 'attachment; filename="result.csv"'
        return response

src/view/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

src/view/templates/index.html
{% load user_filters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>На хайпе</title>
    <!-- Подключаем Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-dark bg-primary mb-5">
        <div class="container">
            <span class="navbar-brand mb-0 h1">На хайпе. Исследование и прогнозирование динамики лояльности участников НПО</span>
        </div>
    </nav>
    
    <div class="container mt-5">
        {% if error_message %}
            <div class="alert alert-danger" role="alert">
                {{ error_message }}
            </div>
        {% endif %}

        <h2>Введите CSV train файл</h2>
        <form id="uploadForm" method="post" enctype="multipart/form-data" action="{% url 'prediction:index'%}">
            {% csrf_token %}
            <div class="form-group">
                <label for="{{ form.csv_file.id_for_label }}" class="form-label">{{ form.csv_file.label }}</label>
                {{ form.csv_file|addclass:'form-control' }}
            </div>
            
            <br>
    
            <button type="submit" class="btn btn-primary" id="uploadButton">Получить результат</button>
        </form>
        <hr>
        <h2>Результат</h2>

        <h3>Полные данные вы можете скачать по ссылке ниже. На сайте демоданные - 500 штук  </h3>
    
        <a href="{% url 'prediction:download_result_file' %}" class="btn btn-primary">Скачать файл</a>
        <br>
        <br>
        <form action="{% url 'prediction:index'%}" method="get">
            <input type="text" name="find_id" placeholder="Поиск по ID" class="form-control">
            <br>
            <button type="submit" class="btn btn-primary">Поиск</button>
            <button type="submit" class="btn btn-secondary">Очистить</button>
        </form>
        <br>
        <div id="predictionTable">
            <div id="predictionTable">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Customer ID</th>
                            <th>Label</th>
                        </tr>
                    </thead>
                    
                    <tbody>
                        {% for prediction in page_obj %}
                            <tr>
                                <td>{{ prediction.customer_id }}</td>
                                <td>{{ prediction.label }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="3">{% include 'includes/paginator.html' %}</td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>

    <!-- Подключаем Bootstrap JS (необязательно) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>